---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashbotdc1-deployment
  labels:
    app: hashbotdc1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hashbotdc1
  template:
    metadata:
      labels:
        app: hashbotdc1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dc
                operator: In
                values:
                - DC1
      containers:
      - name: hashbotdc1
        image: bonifacekabaso/hashbotdc1:1.0.0
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: hashbotdc1-service
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 9000
     nodePort: 30020
  selector:
     app: hashbotdc1
